#!/usr/bin/env python3

__version__ = "0.0.1"

__description__ = """
10X single-cell RNAseq analysis pipeline v{version}

This uses cellranger and is not intended to be run elsewhere.

usage example:
    10X inputdir outputdir mm10
""".format(version=__version__)

import argparse
import subprocess
import yaml
import sys
import os
from glob import glob


def parse_args(defaults={"configfile": None}):
    parser = argparse.ArgumentParser(prog=sys.argv[0])

    parser.add_argument("indir",
                        help="An input directory of gzipped fastq files. The must end with _A_R1.fastq.gz and so on.")

    parser.add_argument("outdir",
                        help="Output directory")

    parser.add_argument("genome",
                        help="genome acronym of target organism (supported: 'dm3', 'dm6', 'hg38', 'mm10')")

    # Options
    parser.add_argument("-c", "--configfile",
                        help="configuration file: config.yaml (default: '%(default)s')",
                        default=defaults["configfile"])

    parser.add_argument("--expect-cells",
                        dest="expectCells",
                        type=int,
                        default=3000,
                        help="The expected number of cells. The cellranger default is 3000.")

    parser.add_argument("--force-cells",
                        dest="forceCells",
                        type=int,
                        required=False,
                        help="Force cellranger to assume there are exactly this many cells.")

    parser.add_argument("--chemistry",
                        choices=["auto", "threeprime", "fiveprime", "SC3Pv1", "SC3Pv2", "SC5P-PE", "SC5P-R2"],
                        default="auto",
                        help="Assay configuration (default 'auto'). See the cellranger documentation for details.")

    parser.add_argument("--maxjobs",
                        type=int,
                        default=30,
                        help="Maximum number of jobs to run at the same time (per-sample). The default is 30.")

    return parser


# Need to handle overrides and the config file
def main():
    ## defaults
    this_script_dir = os.path.dirname(os.path.realpath(__file__))
    defaults = os.path.join(this_script_dir, "defaults.yaml")

    ## get command line arguments
    parser = parse_args(defaults={"configfile": defaults})
    args = parser.parse_args()

    if not os.path.exists(args.indir):
        sys.exit("\nError! Input directory not found! ({})\n".format(args.indir))

    if args.configfile and not os.path.exists(args.configfile):
        sys.exit("\nError! Provided configfile (-c) not found! ({})\n".format(args.configfile))

    os.makedirs(os.path.join(args.outdir, "fastq"), exist_ok=True)

    f = open(args.configfile)
    cf = yaml.load(f)
    f.close()

    # Set the params and genome
    cf['indir'] = os.path.abspath(args.indir)
    cf['outdir'] = os.path.abspath(args.outdir)
    cf['genome'] = cf[args.genome]
    # --overrides???
    params = "--jobmode slurm --disable-ui --nopreflight --maxjobs {}".format(args.maxjobs)
    if args.expectCells:
        params += " --expect-cells {}".format(args.expectCells)
    if args.forceCells:
        params += " --force-cells {}".format(args.forceCells)
    if args.chemistry:
        params += " --chemistry {}".format(args.chemistry)
    cf['params'] = params
    f = open(os.path.join(args.outdir, "10X.config.yaml"), "w")
    yaml.dump(cf, f, default_flow_style=False)
    f.close()

    snakemake_cmd = """
        snakemake --latency-wait {latency_wait} -s {snakefile} --jobs 1 --directory {workingdir} --configfile {configfile}
        """.format(latency_wait = cf["snakemake_latency_wait"],
                   snakefile = os.path.join(this_script_dir, "Snakefile"),
                   workingdir = args.outdir,
                   configfile = os.path.join(args.outdir, '10X.config.yaml')).split()

    p = subprocess.Popen(snakemake_cmd)
    try:
        p.wait()
    except:
        print("\nWARNING: Snakemake terminated!!!")
        if p.returncode != 0:
            print("Returncode:", p.returncode)

            # kill snakemake and child processes
            subprocess.call(["pkill", "-SIGTERM", "-P", str(p.pid)])
            print("SIGTERM sent to PID:", p.pid)

if __name__ == "__main__":
    main()
