snakemake_latency_wait: 300
indir:
outdir:
genome:
sampleSheet:
interop:
mm10: "/data/repository/misc/cellranger-atac/refdata-cellranger-atac-mm10-1.2.0/"
hg38: "/data/repository/misc/cellranger-atac/refdata-cellranger-atac-GRCh38-1.2.0/"
#dm3: "/data/repository/misc/cellranger-atac/refdata-cellranger-atac-dm3"
#dm6: "/data/repository/misc/cellranger-atac/refdata-cellranger-atac-dm6"
