import glob
import os
import yaml
import pandas as pd
import sys
from pathlib import Path
import re
print(config)

# Set proper directories
fqlndir = Path(config['outdir']) / 'fq_ln'
fqlndir.mkdir(parents=True, exist_ok=True)

# Glob over all fastq files in Project directory, and link them in appropriately
for fqfile in list(Path(config['indir']).rglob("*fastq.gz")):
  if 'optical' not in str(fqfile):
    sambase = re.sub(r"_[RI][123].fastq.gz",'',fqfile.name)
    if sambase in config['samples']:
      # R1 from path/sample_R1.fastq.gz
      Rtype = fqfile.with_suffix('').with_suffix('').name.split('_')[-1]
      # sample_S1_L001_I1_001.fastq.gz
      newname = fqlndir / (sambase + '_S1_L001_' + Rtype + '_001.fastq.gz')
      if not newname.exists():
        newname.symlink_to(fqfile)

rule all:
  input:
    expand(
        config['outdir'] + "/{sample}.done",
        sample=config['samples']
    )

rule processSamples:
    output: touch( config['outdir'] + "/{sample}.done" )
    params:
        genome = config['genome'],
        sample = lambda wildcards: wildcards.sample,
        params = config['cellranger_params'],
        fqdir = fqlndir,
        odir = config['outdir']
    shell: """
        cd {params.odir}
        module load cellranger-atac
        cellranger-atac count \
        --fastqs {params.fqdir} \
        --id {params.sample} \
        --reference {params.genome} \
        --sample {params.sample}
        """